
export enum SoundTokens {
  INITIAL = "INITIAL",
  BARKS = "BARKS",
  PROFILES = "PROFILES",
  PAUSE_INITIAL = "PAUSEINITIAL",
  PAUSE_GENERAL_BARKS = "PAUSEGENERALBARKS",
  PAUSE_GENERAL_PROFILES = "PAUSEGENERALPROFILES",
}
